export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_LIST_LATEST_SUCCESS = 'PRODUCT_LIST_LATEST_SUCCESS'
export const PRODUCT_LIST_LATEST_FAIL = 'PRODUCT_LIST_LATEST_FAIL'
