export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_LIST_LATEST_SUCCESS = 'PRODUCT_LIST_LATEST_SUCCESS'
export const PRODUCT_LIST_LATEST_FAIL = 'PRODUCT_LIST_LATEST_FAIL'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
